# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.17rc4.dev121+gfeba2871.d20221214'
__version_tuple__ = version_tuple = (0, 4, 17, 'dev121', 'gfeba2871.d20221214')
