#######################################################################################
# Book settings
title: "Root Viewer" # The title of the book. Will be placed in the left navbar.
logo: images/logo_dark.png # A path to the book logo
author: Daniel Alas # The author of the book
copyright: "2022" # Copyright year to be placed in the footer
only_build_toc_files: false
execute:
  execute_notebooks: cache  # or 'force'

repository:
  url: https://github.com/pyapp-kit/magicgui
  branch: main
  path_to_book: docs

# Not sure how to set system path with yaml, copy this into top of config.py when recreated
#import os, sys
#sys.path.insert(0, os.path.abspath('..'))

sphinx:

  extra_extensions:
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx.ext.autodoc
    - sphinx_autodoc_typehints
    - sphinx.ext.autosummary

  config:
    autosummary_generate: True
    autosummary_imported_members: True
    autodoc_default_options:
        special-members: False
        undoc-members: True
        show-inheritance: True
    templates_path:
      - "_templates"
    html_static_path:
      - "_static"
    html_style: styles.css
    html_show_sourcelink: False
    pygments_style: "default"

    intersphinx_mapping:
      python:
        - "https://docs.python.org/3"
        - null
      napari:
        - "https://napari.org/"
        - null
    html_favicon: "images/favicon.ico"
    html_theme: "sphinx_material"
    html_theme_options:
      repo_url: "https://github.com/wildrootlab/root-viewer"
      repo_name: "wildrood/root-viewer"
      # google_analytics_account: "UA-XXXXX"
      # html_prettify: True
      html_minify: True
      css_minify: True
      repo_type: "github"
      globaltoc_depth: 2
      color_primary: dark-blue
      color_accent: "#66E0F2"
      theme_color: "#51DBBA"
      master_doc: False
      version_dropdown: True,
    html_sidebars:
      "**":
        - globaltoc.html
        - logo-text.html
        - localtoc.html
        - searchbox.html