###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
import os, sys
sys.path.insert(0, os.path.abspath('..'))
author = 'Daniel Alas'
autodoc_default_options = {'special-members': False, 'undoc-members': True, 'show-inheritance': True}
autosummary_generate = True
autosummary_imported_members = True
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2022'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 30
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.viewcode', 'sphinx.ext.napoleon', 'sphinx.ext.autodoc', 'sphinx_autodoc_typehints', 'sphinx.ext.autosummary', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['styles.css', 'styles.css']
html_favicon = 'images/favicon.ico'
html_logo = 'images/logo_dark.png'
html_show_sourcelink = False
html_sidebars = {'**': ['globaltoc.html', 'logo-text.html', 'localtoc.html', 'searchbox.html']}
html_sourcelink_suffix = ''
html_static_path = ['_static', '_static']
html_style = 'styles.css'
html_theme = 'sphinx_material'
html_theme_options = {'repo_url': 'https://github.com/pyapp-kit/magicgui/', 'repo_name': 'wildrood/magicgui', 'html_minify': True, 'css_minify': True, 'repo_type': 'github', 'globaltoc_depth': 2, 'color_primary': 'dark-blue', 'color_accent': '#66E0F2', 'theme_color': '#51DBBA', 'master_doc': False}
html_title = 'Root Viewer'
intersphinx_mapping = {'python': ['https://docs.python.org/3', None], 'napari': ['https://napari.org/', None]}
jupyter_cache = ''
jupyter_execute_notebooks = 'cache'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
pygments_style = 'default'
suppress_warnings = ['myst.domains']
templates_path = ['_templates']
use_jupyterbook_latex = True
use_multitoc_numbering = True
